### ISSUE TITLE
Follow best Unicode best practices

### ISSUE THREAD

**Issue by tkeffer** [weewx/weewx#186]
Right now, weewx generally holds Python `str` objects internally, implicitly encoded in UTF8. Generally, this works, but can lead to problems. For example, a string holding the temperature

```python
>>> a="75°F"
```

is 4 characters long, but it actually holds 5 bytes:

```python
>>> len(a)
5
```

Best practices is to hold strings internally as unicode, converting at the edges. That is, convert from UTF8 on input and output.

**Comment by tkeffer** [comment]
I needed a spot to write down my thoughts, as well as the results of some experimentation. 

I see three approaches:

1. Set `encoding='utf8'` when reading in the `ConfigObjs`. This will cause the entire `config_dict` and `skin_dict` objects to be in unicode. 

    Pro: As far as it goes, simple to implement. 

    Con: This can cause some data structures to become mixed string and unicode. For example, if a new observation type is introduced in `StdCalibrate`, it will be read in as unicode. However, all the other types, which are generally introduced in the drivers, would still be strings. I discovered this problem when `StdPrint` choked because it was being asked to sort a mixed list of strings and unicode. So, either all the drivers have to be changed so they emit only unicode types, or services that could emit unicode types (such as `StdCalibrate`) have to convert then back to regular strings. Or, I suppose, services such as `StdPrint` have to be aware that they might be dealing with mixed string types and be prepared to deal with it.

2. Change to unicode when pulling objects out of a `config_dict` or `skin_dict`.  This is analogous to what we are already doing with other types using helper functions such as `to_int` or `to_bool`.  To implement, we would augment the existing helper function `to_unicode` to allow other data structures (besides strings), such as lists and dictionaries, to be converted. So, for example, the dictionary of image labels in `skin.conf` would be converted to unicode strings when they are pulled out of the `skin_dict`.

    Pro. Follows an established pattern.  Only objects that truly need to be in unicode would be converted. This pattern is already partially implemented in `genplot.py`.

    Con. Will require going through the code looking for such variables.

3. Status quo. Keep all internal strings in `utf8`. 

    Pro. No action necessary. Simple to print things (no conversions necessary).

    Con. Because the code in `genplot.py` already uses option 2 above, the weewx code base will not be entirely consistent in its handling of unicode.


Leaning towards option 2.

**Comment by tkeffer** [comment]
Moving more things to Unicode is causing more problems than its solving, mostly because some of the Python 2.x libraries are not fully Unicode compatible. For example,

~~~python
import time
form=u"temp=%.2f\u00b0"
time.strftime(form,time.localtime(time.time()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 9: ordinal not in range(128)
~~~

To fix this, the format `form` has to be first converted to UTF-8, then the results converted back. While we could do this everywhere in weewx, it seems unreasonable to expect extension writers to recognize this problem.

Another complication is that unicode strings need to be converted to UTF-8 for output. For example:

~~~python
fd=open('junk','w')
print >>fd, form
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 9: ordinal not in range(128)
~~~

There are a few areas of Unicode use that can be cleaned up but, overall, I'm concluding the fix isn't worth the added complexity.
