### ISSUE TITLE
Incorect interval value in MySQL and weex doesnt work because of that. Since version  3.7.1

### ISSUE THREAD

**Issue by tfilo** [weewx/weewx#253]
Since I instaled weex 3.7.1 it writes 0 to column interval in archive table. Because of that weewx doesnt work. Please fix it soon. Before update it was value 5 in interval and everything works fine. Now weewx doesnt work at all because of this error message:
Apr 27 19:56:52 pi weewx[3388]: wmr200: MainThread: I Driver gracefully exiting
Apr 27 19:56:52 pi weewx[3388]: engine: Caught unrecoverable exception in engine:
Apr 27 19:56:52 pi weewx[3388]:     ****  'interval'
Apr 27 19:56:52 pi weewx[3388]:     ****  Traceback (most recent call last):
Apr 27 19:56:52 pi weewx[3388]:     ****    File "/usr/share/weewx/weewx/engine.py", line 871, in main
Apr 27 19:56:52 pi weewx[3388]:     ****      engine.run()
Apr 27 19:56:52 pi weewx[3388]:     ****    File "/usr/share/weewx/weewx/engine.py", line 159, in run
Apr 27 19:56:52 pi weewx[3388]:     ****      self.dispatchEvent(weewx.Event(weewx.STARTUP))
Apr 27 19:56:52 pi weewx[3388]:     ****    File "/usr/share/weewx/weewx/engine.py", line 223, in dispatchEvent
Apr 27 19:56:52 pi weewx[3388]:     ****      callback(event)
Apr 27 19:56:52 pi weewx[3388]:     ****    File "/usr/share/weewx/weewx/engine.py", line 508, in startup
Apr 27 19:56:52 pi weewx[3388]:     ****      self._catchup(self.engine.console.genStartupRecords)
Apr 27 19:56:52 pi weewx[3388]:     ****    File "/usr/share/weewx/weewx/engine.py", line 622, in _catchup
Apr 27 19:56:52 pi weewx[3388]:     ****      origin='hardware'))
Apr 27 19:56:52 pi weewx[3388]:     ****    File "/usr/share/weewx/weewx/engine.py", line 223, in dispatchEvent
Apr 27 19:56:52 pi weewx[3388]:     ****      callback(event)
Apr 27 19:56:52 pi weewx[3388]:     ****    File "/usr/share/weewx/weewx/engine.py", line 588, in new_archive_record
Apr 27 19:56:52 pi weewx[3388]:     ****      dbmanager.addRecord(event.record, accumulator=self.old_accumulator)
Apr 27 19:56:52 pi weewx[3388]:     ****    File "/usr/share/weewx/weewx/manager.py", line 245, in addRecord
Apr 27 19:56:52 pi weewx[3388]:     ****      self._addSingleRecord(record, cursor, log_level)
Apr 27 19:56:52 pi weewx[3388]:     ****    File "/usr/share/weewx/weewx/manager.py", line 1179, in _addSingleRecord
Apr 27 19:56:52 pi weewx[3388]:     ****      _weight = self._calc_weight(record)
Apr 27 19:56:52 pi weewx[3388]:     ****    File "/usr/share/weewx/weewx/manager.py", line 1543, in _calc_weight
Apr 27 19:56:52 pi weewx[3388]:     ****      weight = 60.0 * record['interval'] if self.version >= '2.0' else 1.0
Apr 27 19:56:52 pi weewx[3388]:     ****  KeyError: 'interval'
Apr 27 19:56:52 pi weewx[3388]:     ****  Exiting.

Change in database after update:
mysql> select datetime, archive.interval from archive ORDER BY datetime DESC limit 3;
+------------+----------+
| datetime   | interval |
+------------+----------+
| 1493294902 |        0 |          -- records from 3.7.1
| 1493294400 |        5 |          -- records from 3.6.2
| 1493294100 |        5 |
+------------+----------+

**Comment by tfilo** [comment]
problem by recalculating the weigh
