### ISSUE TITLE
exception during startup when station altitude unit is "feet"

### ISSUE THREAD

**Issue by zerog2k** [weewx/weewx#280]
having "feet" (plural of foot) instead of "foot" as units for altitude in weewx.conf, e.g.
```
altitude = 660, feet
```
causes startup exception.
Possible workaround, be more permissible of variations of unit plurality (e.g., allow feet and foot to mean same thing)

```
Oct 10 09:12:48 spire weewx[8389]:  * Starting weewx weather system weewx
Oct 10 09:12:48 spire weewx[8405]: engine: Initializing weewx version 3.7.1
Oct 10 09:12:48 spire weewx[8405]: engine: Using Python 2.7.12 (default, Nov 19 2016, 06:48:10) #012[GCC 5.4.0 20160609]
Oct 10 09:12:48 spire weewx[8405]: engine: Platform Linux-4.4.0-96-generic-x86_64-with-Ubuntu-16.04-xenial
Oct 10 09:12:48 spire weewx[8405]: engine: Locale is 'en_US.UTF-8'
Oct 10 09:12:48 spire weewx[8405]: engine: pid file is /var/run/weewx.pid
Oct 10 09:12:48 spire weewx[8409]: engine: Using configuration file /etc/weewx/weewx.conf
Oct 10 09:12:48 spire weewx[8409]: engine: Loading station type AcuRite (weewx.drivers.acurite)
Oct 10 09:12:48 spire weewx[8409]: acurite: driver version is 0.24
Oct 10 09:12:48 spire weewx[8409]: acurite: R2 will be decoded using sensor constants
Oct 10 09:12:48 spire weewx[8389]:    ...done.
Oct 10 09:12:48 spire weewx[8409]: engine: StdConvert target unit is 0x1
Oct 10 09:12:48 spire weewx[8409]: engine: Caught unrecoverable exception in engine:
Oct 10 09:12:48 spire weewx[8409]:     ****  'feet'
Oct 10 09:12:48 spire weewx[8409]:     ****  Traceback (most recent call last):
Oct 10 09:12:48 spire weewx[8409]:     ****    File "/usr/share/weewx/weewx/engine.py", line 865, in main
Oct 10 09:12:48 spire weewx[8409]:     ****      engine = engine_class(config_dict)
Oct 10 09:12:48 spire weewx[8409]:     ****    File "/usr/share/weewx/weewx/engine.py", line 77, in __init__
Oct 10 09:12:48 spire weewx[8409]:     ****      self.loadServices(config_dict)
Oct 10 09:12:48 spire weewx[8409]:     ****    File "/usr/share/weewx/weewx/engine.py", line 141, in loadServices
Oct 10 09:12:48 spire weewx[8409]:     ****      self.service_obj.append(weeutil.weeutil._get_object(svc)(self, config_dict))
Oct 10 09:12:48 spire weewx[8409]:     ****    File "/usr/share/weewx/weewx/wxservices.py", line 38, in __init__
Oct 10 09:12:48 spire weewx[8409]:     ****      engine.db_binder)
Oct 10 09:12:48 spire weewx[8409]:     ****    File "/usr/share/weewx/weewx/wxservices.py", line 158, in __init__
Oct 10 09:12:48 spire weewx[8409]:     ****      self.altitude_ft = weewx.units.convert(alt_vt, "foot")[0]
Oct 10 09:12:48 spire weewx[8409]:     ****    File "/usr/share/weewx/weewx/units.py", line 1079, in convert
Oct 10 09:12:48 spire weewx[8409]:     ****      conversion_func = conversionDict[val_t[1]][target_unit_type]
Oct 10 09:12:48 spire weewx[8409]:     ****  KeyError: 'feet'
Oct 10 09:12:48 spire weewx[8409]:     ****  Exiting.

```

**Comment by tkeffer** [comment]
The required unit names are well documented, so I don't see this as a "bug."

As always, a Pull Request is welcome, provided it does not complicate the code too much.
