### ISSUE TITLE
wxformulas not defined lastest acurite driver

### ISSUE THREAD

**Issue by knnniggett** [weewx/weewx#29]
commit 77481e055490ca0101f6331e08f6f6bfb8f09d66 causes the following due to a small typo:
```
Apr 19 07:49:53 pidora weewx[4071]: engine: Caught unrecoverable exception in engine:
Apr 19 07:49:53 pidora weewx[4071]: ****  global name 'wxformulas' is not defined
Apr 19 07:49:53 pidora weewx[4071]: ****  Traceback (most recent call last):
Apr 19 07:49:53 pidora weewx[4071]: ****    File "/usr/share/weewx/weewx/engine.py", line 836, in main
Apr 19 07:49:53 pidora weewx[4071]: ****      engine.run()
Apr 19 07:49:53 pidora weewx[4071]: ****    File "/usr/share/weewx/weewx/engine.py", line 187, in run
Apr 19 07:49:53 pidora weewx[4071]: ****      for packet in self.console.genLoopPackets():
Apr 19 07:49:53 pidora weewx[4071]: ****    File "/usr/share/weewx/weewx/drivers/acurite.py", line 403, in genLoopPackets
Apr 19 07:49:53 pidora weewx[4071]: ****      self._augment_packet(packet)
Apr 19 07:49:53 pidora weewx[4071]: ****    File "/usr/share/weewx/weewx/drivers/acurite.py", line 428, in _augment_packet
Apr 19 07:49:53 pidora weewx[4071]: ****      packet['rain'] = wxformulas.calculate_rain(total, self.last_rain)
Apr 19 07:49:53 pidora weewx[4071]: ****  NameError: global name 'wxformulas' is not defined
Apr 19 07:49:53 pidora weewx[4071]: ****  Exiting.
```
Fix is incoming...

**Comment by matthewwall** [comment]
fixed at commit 9b18deb
