### ISSUE TITLE
Error in vantage file drive of the branch development, to the use the command wee_config --reconfigurate

### ISSUE THREAD

**Issue by h8aluxelare** [weewx/weewx#362]
the output is the next:

```
Installed drivers include:
  0) AcuRite         (weewx.drivers.acurite)   
  1) CC3000          (weewx.drivers.cc3000)    
  2) FineOffsetUSB   (weewx.drivers.fousb)     
  3) Simulator       (weewx.drivers.simulator) 
  4) TE923           (weewx.drivers.te923)     
  5) Ultimeter       (weewx.drivers.ultimeter) 
  6) ?               (weewx.drivers.vantage)   cannot import name int2byte
  7) WMR100          (weewx.drivers.wmr100)    
  8) WMR200          (weewx.drivers.wmr200)    
  9) WMR300          (weewx.drivers.wmr300)    
 10) WMR9x8          (weewx.drivers.wmr9x8)    
 11) WS1             (weewx.drivers.ws1)       
 12) WS23xx          (weewx.drivers.ws23xx)    
 13) WS28xx          (weewx.drivers.ws28xx)    
choose a driver [6]: 
Traceback (most recent call last):
  File "bin/wee_config", line 115, in <module>
    main()
  File "bin/wee_config", line 110, in main
    config_mgr.run(args, options)
  File "/home/weewx/bin/weecfg/config.py", line 102, in run
    self.modify_config(config_dict, options)
  File "/home/weewx/bin/weecfg/config.py", line 120, in modify_config
    stn_info = self.get_stn_info(config_dict, options)
  File "/home/weewx/bin/weecfg/config.py", line 151, in get_stn_info
    stn_info.update(weecfg.prompt_for_driver_settings(driver))
  File "/home/weewx/bin/weecfg/__init__.py", line 1136, in prompt_for_driver_settings
    __import__(driver)
  File "/home/weewx/bin/weewx/drivers/vantage.py", line 18, in <module>
    from weeutil.weeutil import to_int, int2byte
ImportError: cannot import name int2byte

```

**Comment by tkeffer** [comment]
Oops. Forgot about that change in the driver. This error is being caused by running the `vantage.py` driver from the `development` branch using a version of WeeWX from the `master` branch.

Sorry, but you will have to use either the `master` branch, or the `development` branch. They cannot be mixed.
