### ISSUE TITLE
Development branch unicode vs. string type mismatch in weeutil.py under Python2

### ISSUE THREAD

**Issue by UberEclectic** [weewx/weewx#408]
This pertains to validating Python2 compatibility for the development/4.0 branch.
While running under Python2, the engine dies with:

May 14 14:59:24 nixie weewx[348]: manager: Added record 2019-05-14 13:04:00 EDT (1557853440) to database 'weewx.sdb'
May 14 14:59:24 nixie weewx[348]: Added record 2019-05-14 13:04:00 EDT (1557853440) to daily summary in 'weewx.sdb'
May 14 14:59:24 nixie weewx[348]: engine: Main loop exiting. Shutting engine down.
May 14 14:59:24 nixie weewx[348]: restx: Shut down Wunderground-RF thread.
May 14 14:59:25 nixie weewx[348]: restx: Shut down Wunderground-PWS thread.
May 14 14:59:25 nixie weewx[348]: engine: Caught unrecoverable exception in engine:
May 14 14:59:25 nixie weewx[348]:     ****  descriptor 'lower' requires a 'str' object but received a 'unicode'
May 14 14:59:25 nixie weewx[348]:     ****  : Traceback (most recent call last):
May 14 14:59:25 nixie weewx[348]:     ****  :   File "/usr/share/weewx/bin/weewx/engine.py", line 898, in main
May 14 14:59:25 nixie weewx[348]:     ****  :     engine.run()
May 14 14:59:25 nixie weewx[348]:     ****  :   File "/usr/share/weewx/bin/weewx/engine.py", line 161, in run
May 14 14:59:25 nixie weewx[348]:     ****  :     self.dispatchEvent(weewx.Event(weewx.STARTUP))
May 14 14:59:25 nixie weewx[348]:     ****  :   File "/usr/share/weewx/bin/weewx/engine.py", line 228, in dispatchEvent
May 14 14:59:25 nixie weewx[348]:     ****  :     callback(event)
May 14 14:59:25 nixie weewx[348]:     ****  :   File "/usr/share/weewx/bin/weewx/engine.py", line 524, in startup
May 14 14:59:26 nixie weewx[348]:     ****  :     self._catchup(self.engine.console.genStartupRecords)
May 14 14:59:26 nixie weewx[348]:     ****  :   File "/usr/share/weewx/bin/weewx/engine.py", line 639, in _catchup
May 14 14:59:26 nixie weewx[348]:     ****  :     origin='hardware'))
May 14 14:59:26 nixie weewx[348]:     ****  :   File "/usr/share/weewx/bin/weewx/engine.py", line 228, in dispatchEvent
May 14 14:59:26 nixie weewx[348]:     ****  :     callback(event)
May 14 14:59:26 nixie weewx[348]:     ****  :   File "/usr/share/weewx/bin/weewx/engine.py", line 735, in new_archive_record
May 14 14:59:26 nixie weewx[348]:     ****  :     to_sorted_string(event.record).encode('utf-8'))
May 14 14:59:26 nixie weewx[348]:     ****  :   File "/usr/share/weewx/bin/weeutil/weeutil.py", line 1374, in to_sorted_string
May 14 14:59:26 nixie weewx[348]:     ****  :     return ", ".join(["%s: %s" % (k, rec.get(k)) for k in sorted(rec, key=str.lower)])
May 14 14:59:26 nixie weewx[348]:     ****  : TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'
May 14 14:59:26 nixie weewx[348]:     ****  Exiting.
May 14 14:59:26 nixie systemd[1]: weewx.service: Main process exited, code=exited, status=1/FAILURE
May 14 14:59:26 nixie systemd[1]: weewx.service: Unit entered failed state.
May 14 14:59:26 nixie systemd[1]: weewx.service: Failed with result 'exit-code'.

I'm stumped on this one, because, out of the box we have:

May 14 18:09:03 nixie weewx[4935]:     ****  :     return ", ".join(["%s: %s" % (k, rec.get(k)) for k in sorted(rec, key=str.lower)])
May 14 18:09:03 nixie weewx[4935]:     ****  : TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'

But if I change that str.lower to unicode.lower, we get the opposite:

May 14 18:12:24 nixie weewx[4973]:     ****  :     return ", ".join(["%s: %s" % (k, rec.get(k)) for k in sorted(rec, key=unicode.lower)])
May 14 18:12:24 nixie weewx[4973]:     ****  : TypeError: descriptor 'lower' requires a 'unicode' object but received a 'str'

Reverted to the str.lower and switched to Python3, after which the above error does not occur.

**Comment by UberEclectic** [comment]
Still trying to get my head around the issue when running under Python2.
Since the crash happens almost immediately after the wmr300.py driver initialized and control is passed back to engine.py, I went looking for references to function to_sorted_string() in wmr300.py.

Sure enough, right at the end of wmr300.py we have:

```
    if options.get_history:
        ts = time.time() - 3600 # get last hour of data
        for pkt in stn.genStartupRecords(ts):
            print(to_sorted_string(pkt))

    if options.get_current:
        for packet in stn.genLoopPackets():
            print(to_sorted_string(packet))
```

But compare that usage to what engine.py itself does when making the call:

```
    def new_loop_packet(self, event):
        """Print out the new LOOP packet"""
        print("LOOP:  ",
              weeutil.weeutil.timestamp_to_string(event.packet['dateTime']),
              to_sorted_string(event.packet).encode('utf-8'))

    def new_archive_record(self, event):
        """Print out the new archive record."""
        print("REC:   ",
              weeutil.weeutil.timestamp_to_string(event.record['dateTime']),
              to_sorted_string(event.record).encode('utf-8'))
```

Notice that each call from within engine.py is being explicitly passed through .encode('utf-8'), but not so in wmr300.py.

My thinking is this all works in Python3, because strings are inherently unicode, but under Python2, the wmr300.py is passing strings to to_sorted_string(), where as the engine.py is passing unicode, and so there is a Type disagreement.

Thoughts?

So might the fix (to make the code Python2 compatible) be as follows on the wmr300.py side?

```
    if options.get_history:
        ts = time.time() - 3600 # get last hour of data
        for pkt in stn.genStartupRecords(ts):
            print(to_sorted_string(pkt).encode('utf-8'))

    if options.get_current:
        for packet in stn.genLoopPackets():
            print(to_sorted_string(packet).encode('utf-8'))
```

**Comment by UberEclectic** [comment]
Bingo!  With the addition of .encode('utf-8') in wmr300.py for each call to to_sorted_string(), the handoff between wmr300.py and engine.py now works under both Python2 and Python3.  Yay!

**Comment by UberEclectic** [comment]
Tom, Pull request #407 has the goods.  So it would seem that ultimately I did find a way to validate your changes to wmr300.py that you made with Python3 in mind, and did find just the one issue with to_sorted_string() calls missing an explicit .encode('utf-8').

**Comment by UberEclectic** [comment]
For posterity, if I am understanding correctly, this is the change from "queue" to "q" that led to wunderfixer also needing such a change:

https://github.com/weewx/weewx/commit/f1003407dcbdffc0b7416f7c709f9c510c0054fc#diff-3543cd71b0a5b03d640fdd68611c5e68

**Comment by UberEclectic** [comment]
The clean pull is #409 (which replaces #407).
