### ISSUE TITLE
Unable to run Weewx

### ISSUE THREAD

**Issue by mox575** [weewx/weewx#444]
Let me start by saying that I am new to Python, so please bear with me. After installing python and weewx and following the process that was laid out here: https://github.com/weewx/weewx/wiki/weewx-on-windows , I attempted to Run Weewx. I received several errors and they are as follows:
PS C:\Users\weewx> python bin\weewxd weewx.conf
Traceback (most recent call last):
  File "bin\weewxd", line 64, in <module>
    weewx.engine.main(options, args)
  File "C:\Users\weewx\bin\weewx\engine.py", line 891, in main
    engine = engine_class(config_dict)
  File "C:\Users\weewx\bin\weewx\engine.py", line 72, in __init__
    self.setupStation(config_dict)
  File "C:\Users\weewx\bin\weewx\engine.py", line 90, in setupStation
    driver = config_dict[stationType]['driver']
  File "C:\Python27\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'unspecified'

Any assistance would be appreciated.

**Comment by tkeffer** [comment]
Hello. This issues list is for tracking bugs and enhancements. Please direct your question to the User's Group, [weewx-user](https://groups.google.com/forum/#!forum/weewx-user).
