### ISSUE TITLE
Unable to install weewx-crt

### ISSUE THREAD

**Issue by G400** [weewx/weewx#559]
[https://github.com/weewx/weewx/issues/558](url)
Assuming a typo in the documentation.  
From documentation:
Download file:
wget -O weewx-crt.zip https://github.com/matthewwall/weewx-crt/archive/master.zip

Guessing install install 'weewx-crt.tgz should be weewx-crt.zip. Inspecting header of file also confirms this is a zip file.

Still no luck:
sudo wee_extension --install weewx-crt.zip
Request to install 'weewx-crt.zip'
Extracting from zip archive weewx-crt.zip
Traceback (most recent call last):
File "/usr/share/weewx/wee_extension", line 88, in
main()
File "/usr/share/weewx/wee_extension", line 80, in main
ext.install_extension(options.install)
File "/usr/share/weewx/weecfg/extension.py", line 113, in install_extension
self.tmpdir, self.logger)
File "/usr/share/weewx/weecfg/init.py", line 1760, in extract_zip
zip_archive = zipfile.ZipFile(filename)
File "/usr/lib/python3.7/zipfile.py", line 1222, in init
self._RealGetContents()
File "/usr/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by tkeffer** [comment]
crt is not part of WeeWX. You should post an issue on its site.
