### ISSUE TITLE
Extension throws errors in Log - No data upload

### ISSUE THREAD

**Issue by magnum61** [weewx/weewx#600]
I tried to use the extension in my V4.1.1 install, but ended up with errors in the logs, no data is transferred to wetter.com

Log contain:

```
Sep  3 14:42:23 weewx[23097] ERROR weewx.restx: Wetter: Unexpected exception of type <class 'TypeError'>
Sep  3 14:42:23 weewx[23097] ERROR weewx.restx: *** Traceback (most recent call last):
Sep  3 14:42:23 weewx[23097] ERROR weewx.restx: ***   File "/usr/share/weewx/weewx/restx.py", line 378, in run_loop
Sep  3 14:42:23 weewx[23097] ERROR weewx.restx: ***     self.process_record(_record, dbmanager)
Sep  3 14:42:23 weewx[23097] ERROR weewx.restx: ***   File "/usr/share/weewx/weewx/restx.py", line 442, in process_record
Sep  3 14:42:23 weewx[23097] ERROR weewx.restx: ***     self.post_with_retries(_request, data)
Sep  3 14:42:23 weewx[23097] ERROR weewx.restx: ***   File "/usr/share/weewx/weewx/restx.py", line 484, in post_with_retries
Sep  3 14:42:23 weewx[23097] ERROR weewx.restx: ***     self.check_response(_response)
Sep  3 14:42:23 weewx[23097] ERROR weewx.restx: ***   File "/usr/share/weewx/user/wetter.py", line 143, in check_response
Sep  3 14:42:23 weewx[23097] ERROR weewx.restx: ***     if txt.find('"errorcode":"100"') != -1 or \
Sep  3 14:42:23 weewx[23097] ERROR weewx.restx: *** TypeError: argument should be integer or bytes-like object, not 'str'
Sep  3 14:42:23 weewx[23097] CRITICAL weewx.restx: Wetter: Thread terminating. Reason: argument should be integer or bytes-like object, not 'str'
```

**Comment by tkeffer** [comment]
See issue https://github.com/weewx/weewx/issues/599
