### ISSUE TITLE
`wee_import` fails if null bytes are encountered an import file

### ISSUE THREAD

**Issue by gjr80** [weewx/weewx#607]
There have been a number of cases where one or more null bytes in a `wee_import` data file have caused an import to fail. The null bytes cause the `csv.DictReader()` to raise a `csv.Error` as evidenced in this `wee_import` console output extract:
```
Obtaining raw import data for period 1 ...
Traceback (most recent call last):
  File "/usr/share/weewx/wee_import", line 900, in <module>
    main()
  File "/usr/share/weewx/wee_import", line 830, in main
    source_obj.run()
  File "/usr/share/weewx/weeimport/weeimport.py", line 368, in run
    _raw_data = self.getRawData(period)
  File "/usr/share/weewx/weeimport/wdimport.py", line 568, in getRawData
    for rec in _reader:
  File "/usr/lib/python3.7/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
```
CSV, WD and Cumulus imports use `csv.DictReader()` to process raw data but anecdotally the null byte problem seems to occur mainly with WD and Cumulus imports and not with CSV imports. This may be due to the source/construction of the files, the WD and Cumulus monthly log files are used as the import source files and these files are delimited text files produced by appending one line at a time to an existing file. Some files have upwards of 40 000 lines. Should WD/Cumulus be terminated or restarted abnormally these files could be malformed. CSV import files (again anecdotally) seem to be more often generated in a one-shot scenario rather than constructed one line at a time over a long period.

A simple solution is to filter each line before it is processed by `csv.DictReader()` and remove any null bytes. This may or may not result in erroneous data being passed to `csv.DictReader()` which may be subsequently imported though again anecdotally most cases seem to have had the null byte at the start or end of a line which would not affect the underlying data. This situation could be mitigated by logging the null byte line number as well as displaying the line number of the console during import. This solution has worked on a test system and should be tried on a live system via [this weewx-user thread](https://groups.google.com/g/weewx-user/c/5Z6GrXCDSvo). If successful this approach will be applied to the CSV and Cumulus `wee_import` modules as well.

**Comment by gjr80** [comment]
Filtering and logging of null bytes was successful in the CSV import module and has been applied to the WD, Cumulus and WeatherCat modules as well. Commits 9fbd0a8c8cbd4408ad37b47a907e9171622ce6e8, 87c5861e750f6a2b2d199a7400d88ddca5a7eb28, b10ffbb128795ec9d635203ad6c4434fe2a07841, b85160e8c6531856339e930604e7666eb3a61dd4 and refer. The WU import module uses the WU API to obtain data rather than a PWS software generated data file. So far the WU import module has been immune to this issue and consequently has not been similarly changed.

These changes appeared in v4.2.0 but were not included in the change log. Entry added to change log for historical purposes at commit 877e8793e8286fb00dfb2aa8459c2c4eb9e75687.
