### ISSUE TITLE
crash with bogus units for altitude

### ISSUE THREAD

**Issue by vinceskahan** [weewx/weewx#687]
(from weewx-user) we have a recent [report](https://groups.google.com/g/weewx-user/c/DSuLT89IOC0) in the thread 'Problem with GW1000 driver' in which weewx crashes if a bogus unit (in this case 'feet' rather than the correct units of 'foot' is used for altitude, without much helpful information.

It would be helpful if weewx logs 'why' it is aborting so that the user knows what to fix.    Alternate solutions such as some kind of pre-check on weewx.conf for these kinds of syntax errors might be worth thinking about as well.

**Comment by gjr80** [comment]
WeeWX reports such a config error just fine:
```
Aug 10 03:36:13 buster31 weewx[731]: Starting weewx weather system: weewx.
Aug 10 03:36:13 buster31 weewx[742] INFO __main__: Locale is 'en_AU.UTF-8'
Aug 10 03:36:13 buster31 weewx[742] INFO __main__: PID file is /var/run/weewx.pid
Aug 10 03:36:13 buster31 weewx[746] INFO __main__: Using configuration file /home/weewx/weewx.conf
Aug 10 03:36:13 buster31 weewx[746] INFO __main__: Debug is 1
Aug 10 03:36:13 buster31 weewx[746] DEBUG __main__: Initializing engine
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.engine: Loading station type Simulator (weewx.drivers.simulator)
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.engine.StdTimeSynch
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.engine.StdTimeSynch
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.engine.StdConvert
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.engine: StdConvert target unit is 0x1
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.engine.StdConvert
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.engine.StdCalibrate
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.engine.StdCalibrate
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.engine.StdQC
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.engine.StdQC
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.wxservices.StdWXCalculate
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.wxservices: StdWXCalculate will use data binding wx_binding
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.manager: Daily summary version is 4.0
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.wxservices.StdWXCalculate
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdWXXTypes
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdWXXTypes
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdPressureCooker
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdPressureCooker
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdRainRater
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdRainRater
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdDelta
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdDelta
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.engine.StdArchive
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.engine: Archive will use data binding wx_binding
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.engine: Record generation will be attempted in 'hardware'
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.engine: Using archive interval of 60 seconds (specified in weewx configuration)
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Use LOOP data in hi/low calculations: 1
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.engine.StdArchive
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.restx.StdStationRegistry
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.restx: StationRegistry: Registration not requested.
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.restx.StdStationRegistry
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.restx.StdWunderground
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.restx: Wunderground: Posting not enabled.
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.restx.StdWunderground
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.restx.StdPWSweather
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.restx: PWSweather: Posting not enabled.
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.restx.StdPWSweather
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.restx.StdCWOP
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.restx: CWOP: Posting not enabled.
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.restx.StdCWOP
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.restx.StdWOW
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.restx: WOW: Posting not enabled.
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.restx.StdWOW
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.restx.StdAWEKAS
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.restx: AWEKAS: Posting not enabled.
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.restx.StdAWEKAS
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.engine.StdPrint
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.engine.StdPrint
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Loading service weewx.engine.StdReport
Aug 10 03:36:13 buster31 weewx[746] DEBUG weewx.engine: Finished loading service weewx.engine.StdReport
Aug 10 03:36:13 buster31 weewx[746] INFO __main__: Starting up weewx version 4.6.0a1
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.engine: Clock error is -0.04 seconds (positive is fast)
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.manager: Starting backfill of daily summaries
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.manager: Daily summaries up to date
Aug 10 03:36:13 buster31 weewx[746] INFO weewx.engine: Starting main packet loop.
Aug 10 03:36:16 buster31 weewx[746] DEBUG weewx.units: Unable to convert from feet to foot
Aug 10 03:36:16 buster31 weewx[746] INFO weewx.engine: Main loop exiting. Shutting engine down.
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__: Caught unrecoverable exception:
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****  'feet'
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****  Traceback (most recent call last):
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****    File "/home/weewx/bin/weewxd", line 157, in main
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****      engine.run()
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 210, in run
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.NEW_LOOP_PACKET, packet=packet))
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 245, in dispatchEvent
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****      callback(event)
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/wxservices.py", line 112, in new_loop_packet
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****      self.do_calculations(event.packet, self.loop_calc_dict)
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/wxservices.py", line 137, in do_calculations
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****      new_value = weewx.xtypes.get_scalar(obs_type, data_dict, self.db_manager)
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/xtypes.py", line 73, in get_scalar
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****      return xtype.get_scalar(obs_type, record, db_manager)
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/wxxtypes.py", line 381, in get_scalar
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****      return self.altimeter(record)
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/wxxtypes.py", line 430, in altimeter
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****      altitude = weewx.units.convertStd(self.altitude_vt, record['usUnits'])
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/units.py", line 1605, in convertStd
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****      return StdUnitConverters[target_std_unit_system].convert(val_t)
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/units.py", line 1023, in convert
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****      new_val_t = convert(val_t, new_unit_type)
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/units.py", line 1569, in convert
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****      conversion_func = conversionDict[val_t[1]][target_unit]
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****  KeyError: 'feet'
Aug 10 03:36:16 buster31 weewx[746] CRITICAL __main__:     ****  Exiting.
```

I suspect you will find the issue is the OP's system, for some reason it was not logging anything higher than INFO, it certainly was not logging what we would expect when `debug = 1`.

**Comment by vinceskahan** [comment]
Agreed.   I'm good with canceling this one.
