### ISSUE TITLE
formatting of cheetah failure could use some improvement

### ISSUE THREAD

**Issue by matthewwall** [weewx/weewx#700]
i had a syntax error in one of the .inc files that was included in my template file.  cheetah choked on it, and weewx reported this in the log.

on the plus side, weewx is now providing better information about where/why cheetah is failing.  on the minus side, the information is not presented very well.

the 'Reason' log entry contains escaped characters (all of the `#012` and other codes) which are rather confusing.  but the nicely formatted reason (at the end of the stack trace) also includes the rest of a stack trace, which is useless to anyone debugging their template files.

ideally i would like to see only the 'Ignoring template' and 'Reason' log entries, but with the 'Reason' entry formatted properly instead of escaped into a single line.

here is sample output from the log:
```
Sep 20 00:05:25 data weewx-sdr[16775] INFO weewx.manager: Added record 2021-09-20 00:05:00 EDT (1632110700) to database 'sdr.sdb'
Sep 20 00:05:25 data weewx-sdr[16775] INFO weewx.manager: Added record 2021-09-20 00:05:00 EDT (1632110700) to daily summary in 'sdr.sdb'
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'Cheetah.Parser.ParseError'>'
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: **** Ignoring template /opt/weewx-skins/drivein-control/index.html.tmpl
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: **** Reason: #012#012EOF was reached before a matching ')' was found for the '('#012Line 72, column 43 in file /opt/weewx-skins/drivein-control/sensors.inc#012#012Line|Cheetah Code#012----|-------------------------------------------------------------#01269  |  #if getattr($current, $x).has_data#01270  |    <tr>#01271  |      <td class="label">getattr($obs, $x).label</td>#01272  |      <td class="data">$get_battery_status(getattr($current, $x).raw</td>#012                                               ^#01273  |    </tr>#01274  |  #end if#01275  |#end for
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****    File "/opt/weewx/bin/weewx/cheetahgenerator.py", line 321, in generate
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****    File "cheetah__opt_weewx_skins_drivein_control_index_html_tmpl_1632110725_72_32873.py", line 121, in respond
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1685, in _handleCheetahInclude
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****      file=file)
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 775, in compile
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****      compiler.compile()
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Compiler.py", line 1799, in compile
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****      self._parser.parse()
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Parser.py", line 1542, in parse
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****      self.eatPlaceholder()
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Parser.py", line 1624, in eatPlaceholder
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****      allowCacheTokens=True, returnEverything=True)
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Parser.py", line 1347, in getPlaceholder
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****      nameChunks = self.getCheetahVarNameChunks()
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Parser.py", line 949, in getCheetahVarNameChunks
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****      rest = self.getCallArgString()
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Parser.py", line 998, in getCallArgString
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****      "' was found for the '" + open + "'")
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  ParseError: 
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  EOF was reached before a matching ')' was found for the '('
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  Line 72, column 43 in file /opt/weewx-skins/drivein-control/sensors.inc
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  Line|Cheetah Code
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  ----|-------------------------------------------------------------
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  69  |  #if getattr($current, $x).has_data
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  70  |    <tr>
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  71  |      <td class="label">getattr($obs, $x).label</td>
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  72  |      <td class="data">$get_battery_status(getattr($current, $x).raw</td>
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****                                                 ^
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  73  |    </tr>
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  74  |  #end if
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  75  |#end for
Sep 20 00:05:25 data weewx-sdr[16775] ERROR weewx.cheetahgenerator: ****  
Sep 20 00:05:25 data weewx-sdr[16775] INFO weewx.cheetahgenerator: Generated 0 files for report drivein-control in 0.18 seconds
Sep 20 00:05:26 data weewx-sdr[16775] INFO weewx.imagegenerator: Generated 4 images for report drivein-control in 0.22 seconds
Sep 20 00:05:26 data weewx-sdr[16775] INFO weewx.reportengine: Copied 0 files to /var/www/html/sdr
```

**Comment by matthewwall** [comment]
this is weewx 4.1.1 running on debian 10
