### ISSUE TITLE
Missing config option to select non standard port on MySQL

### ISSUE THREAD

**Issue by g-vidal** [weewx/weewx#73]
hello,

I have not been able to find how to select a non standard port (other than 3306) to connect to mysql database. I suspect this is the underlying problem for this error :
```shell
sudo wee_database --create-archive
Using configuration file /etc/weewx/weewx.conf
Using database binding 'wx_binding', which is bound to database 'archive_mysql'
Traceback (most recent call last):
  File "/usr/bin/wee_database", line 264, in <module>
    main()
  File "/usr/bin/wee_database", line 83, in main
    createMainDatabase(config_dict, db_binding)
  File "/usr/bin/wee_database", line 107, in createMainDatabase
    with weewx.manager.open_manager_with_config(config_dict, db_binding, initialize=True) as dbmanager:
  File "/usr/share/weewx/weewx/manager.py", line 986, in open_manager_with_config
    return open_manager(manager_dict, initialize)
  File "/usr/share/weewx/weewx/manager.py", line 975, in open_manager
    manager_dict['schema'])
  File "/usr/share/weewx/weewx/manager.py", line 132, in open_with_create
    weedb.create(database_dict)
  File "/usr/share/weewx/weedb/__init__.py", line 54, in create
    return driver_mod.create(**db_dict)
  File "/usr/share/weewx/weedb/mysql.py", line 57, in create
    raise weedb.OperationalError(e)
weedb.OperationalError: (2003, "Can't connect to MySQL server on 'xxxxxxx.yyyyyyyyyy.fr' (111)")
```

I have checked the user and password from weewx.conf on phpmyadmin it works, the database name given is OK also.

I have also tried to add the port at the end of the computer adress with another error : 

```sh
weedb.OperationalError: (2005, "Unknown MySQL server host 'xxxxxxxxxx.yyyyyyy.fr:3205' (0)")
```
We have another software that works with that command :

```php
<?php
$server ="xxxxxxx.yyyyyyy.fr:3205";
$user="XXXXXXX";
$pass="YYYYYYYYYYY";
$db="lacrosse_data";
mysql_connect($server,$user,$pass) or die ("Erreur SQL : ".mysql_error() );
mysql_select_db($db) or die ("Erreur SQL : ".mysql_error() );
?>
```

Is there any way to configure mysql port or  could you please introduce an option in the config file.

Thanks for your great work, let me know if I may help.
best regards

**Comment by tkeffer** [comment]
Fixed in commit 3d578aea161ecb3cd4632e6d19cb926c7c4bcdc0. 
You can now specify an optional keyword `port`, which will default to 3306.
