### ISSUE TITLE
imagegenerator dies when it encounters an observation that is not in the db schema

### ISSUE THREAD

**Issue by matthewwall** [weewx/weewx#735]
if there is an observation specified in the imagegenerator configuration, and that observation does not exist in the database schema, the imagegenerator dies.  this is rather hostile behavior.  it would be better to make note of the discrepancy in a DEBUG log message - analogous to the cheetah generator not dying when it encounters an unknown tag, but just logging it in a DEBUG message instead.

weewx version: 4.6 latest as of 22jan2022 (probably every older version too)

how to repeat: run the Seasons skin with a database whose schema does not include one of the 'standard' fields, for example outTemp or windSpeed.

```
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.imagegenerator.ImageGenerator'
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****  no such column: windSpeed
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****    File "/opt/weewx-220117/bin/weewx/reportengine.py", line 197, in run
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****      obj.start()
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****    File "/opt/weewx-220117/bin/weewx/reportengine.py", line 378, in start
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****      self.run()
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****    File "/opt/weewx-220117/bin/weewx/imagegenerator.py", line 42, in run
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****      self.gen_images(self.gen_ts)
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****    File "/opt/weewx-220117/bin/weewx/imagegenerator.py", line 109, in gen_images
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****      self.image_dict[timespan][plotname])
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****    File "/opt/weewx-220117/bin/weewx/imagegenerator.py", line 209, in gen_plot
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****      skip = _skip_if_empty(db_manager, var_type, check_domain)
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****    File "/opt/weewx-220117/bin/weewx/imagegenerator.py", line 424, in _skip_if_empty
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****      val = weewx.xtypes.get_aggregate(var_type, check_domain, 'not_null', db_manager)
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****    File "/opt/weewx-220117/bin/weewx/xtypes.py", line 128, in get_aggregate
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****      **option_dict)
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****    File "/opt/weewx-220117/bin/weewx/xtypes.py", line 867, in get_aggregate
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****      row = db_manager.getSql(select_stmt)
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****    File "/opt/weewx-220117/bin/weewx/manager.py", line 463, in getSql
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****      _cursor.execute(sql, sqlargs)
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****    File "/opt/weewx-220117/bin/weedb/sqlite.py", line 42, in guarded_fn
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****      raise weedb.NoColumnError(e)
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****  NoColumnError: no such column: windSpeed
Jan 22 10:40:35 7up weewx-sds011[28980] ERROR weewx.reportengine:         ****  Generator terminated
```

preferred result: DEBUG log message something like this:
```
DEBUG weewx.imagegenerator: NoColumnError: no such column: windSpeed
```

for reference, this is what you see from cheetahgenerator for the analogous situation in template files:

```
Jan 22 10:45:35 7up weewx-sds011[28980] DEBUG weewx.cheetahgenerator: Unrecognized: $year.inTemp.mintime
Jan 22 10:45:35 7up weewx-sds011[28980] DEBUG weewx.cheetahgenerator: Unrecognized: $year.inTemp.max
Jan 22 10:45:35 7up weewx-sds011[28980] DEBUG weewx.cheetahgenerator: Unrecognized: $year.inTemp.maxtime
Jan 22 10:45:35 7up weewx-sds011[28980] DEBUG weewx.cheetahgenerator: Unrecognized: $year.barometer.min
Jan 22 10:45:35 7up weewx-sds011[28980] DEBUG weewx.cheetahgenerator: Unrecognized: $year.barometer.mintime
Jan 22 10:45:35 7up weewx-sds011[28980] DEBUG weewx.cheetahgenerator: Unrecognized: $year.barometer.max
Jan 22 10:45:35 7up weewx-sds011[28980] DEBUG weewx.cheetahgenerator: Unrecognized: $year.barometer.maxtime
Jan 22 10:45:35 7up weewx-sds011[28980] DEBUG weewx.cheetahgenerator: Unrecognized: $year.wind.max
Jan 22 10:45:35 7up weewx-sds011[28980] DEBUG weewx.cheetahgenerator: Unrecognized: $year.wind.gustdir
Jan 22 10:45:35 7up weewx-sds011[28980] DEBUG weewx.cheetahgenerator: Unrecognized: $year.wind.maxtime
```

**Comment by matthewwall** [comment]
fixed at commit 08cb092

it turns out that it is not appropriate to log the error, at least not at this level
