### ISSUE TITLE
wee_database fails with a text field

### ISSUE THREAD

**Issue by glennmckechnie** [weewx/weewx#738]
This is in reference to the last entry on [this thread](https://groups.google.com/g/weewx-user/c/afPbV04SDjs) where TEXT fields are [an option for the database]( https://github.com/weewx/weewx/wiki/Storing-text-in-the-database). I was testing for (known) Null strings and it also had a Text column, with entries. It fell over on the Text entries.

This was on weewx.4.5.1

==== If a database with a field type of TEXT is checked using `wee_database --check-strings` it fails with the following stack trace.

```
:graybeard@whitebeard:/home/weewx/bin
06:50 PM $ ./wee_database --check-strings
Using configuration file /home/weewx451/weewx.conf
Using database binding 'wx_binding', which is bound to database 'archive_sqlite'
Preparing Null String Fix, this may take a while...
Traceback (most recent call last):
  File "./wee_database", line 1138, in <module>
    main()
  File "./wee_database", line 227, in main
    check_strings(config_dict, db_binding, options, fix=False)
  File "./wee_database", line 934, in check_strings
    if record[icol] is not None and not check_type(record[icol], obs_type_list[icol]):
  File "./wee_database", line 879, in check_type
    raise ValueError("Unknown type %s" % expected)
ValueError: Unknown type TEXT
```

====== FIXED (for me) with the following changes to wee_database

```
xterm root@whitebeard:/home
04:44 PM $ diff -au weewx451/bin/wee_database weewx451/bin/wee_database-text 
--- weewx451/bin/wee_database   2021-04-03 06:02:14.000000000 +1100
+++ weewx451/bin/wee_database-text      2022-01-22 16:25:26.293912710 +1100
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/python3
 #
 #    Copyright (c) 2009-2021 Tom Keffer <tkeffer@gmail.com>
 #
@@ -875,6 +875,8 @@
         return isinstance(val, float)
     elif expected == 'STR':
         return isinstance(val, six.string_types)
+    elif expected == 'TEXT':
+        return isinstance(val, six.string_types)
     else:
         raise ValueError("Unknown type %s" % expected)
 
@@ -886,6 +888,8 @@
         return float(val)
     elif target == 'STR':
         return six.ensure_str(val)
+    elif target == 'TEXT':
+        return six.ensure_str(val)
     else:
         raise ValueError("Unknown type %s" % target)


```
==== Null strings in test record (which also has a TEXT field) are then detected as expected.

```
:graybeard@whitebeard:/home/weewx/bin
07:34 PM $ sudo ./wee_database --fix-strings
Using configuration file /home/weewx451/weewx.conf
Using database binding 'wx_binding', which is bound to database 'archive_sqlite'
Preparing Null String Fix, this may take a while...
 hecking record: 253; Timestamp: 2022-01-17 16:50:00 AEDT (1642398600)
The following null strings were found:
Timestamp = 1641720720; record['extraTemp1'] = 'Null'; ... changed to None
Timestamp = 1641720720; record['extraTemp2'] = 'Null'; ... changed to None
Timestamp = 1641720720; record['extraTemp3'] = 'Null'; ... changed to None
3 of 3 null strings found were fixed.
Applied Null String Fix in 0.29 seconds.
```

**Comment by gjr80** [comment]
Fixed at commit 35e1d483c777656c0442dd825926649e063befc6. To appear in 4.6.1.
