### ISSUE TITLE
Engine.py (4.6.1) crashes after attempting to compare two incompatible variable types float and none

### ISSUE THREAD

**Issue by mytechguyri** [weewx/weewx#747]
Feb 11 01:50:17 direwolf user.info weewx[4789] INFO weewx.manager: Added record 2022-02-11 01:50:00 EST (1644562200) to database 'weewx'
Feb 11 01:50:18 direwolf user.info weewx[4789] INFO weewx.manager: Added record 2022-02-11 01:50:00 EST (1644562200) to daily summary in 'weewx'
Feb 11 01:50:18 direwolf user.info weewx[4789] INFO weewx.engine: Main loop exiting. Shutting engine down.
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__: Caught unrecoverable exception:
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****  '>' not supported between instances of 'float' and 'NoneType'
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****  Traceback (most recent call last):
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 214, in run
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.CHECK_LOOP, packet=packet))
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 245, in dispatchEvent
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****      callback(event)
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 634, in check_loop
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****      raise BreakLoop
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****  weewx.engine.BreakLoop
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****  During handling of the above exception, another exception occurred:
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****  Traceback (most recent call last):
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 153, in main
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****      engine.run()
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 221, in run
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.POST_LOOP))
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 245, in dispatchEvent
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****      callback(event)
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 644, in post_loop
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****      self._software_catchup()
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 715, in _software_catchup
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****      self.engine.dispatchEvent(weewx.Event(weewx.NEW_ARCHIVE_RECORD,
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 245, in dispatchEvent
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****      callback(event)
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****    File "/usr/share/weewx/user/forecast.py", line 1212, in update_forecast
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****      elif time.time() - self.interval > self.last_ts:
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****  TypeError: '>' not supported between instances of 'float' and 'NoneType'
Feb 11 01:50:18 direwolf user.crit weewx[4789] CRITICAL __main__:     ****  Exiting.

**Comment by mytechguyri** [comment]
Disregard.... The error is in the add-on forecast module.
