### ISSUE TITLE
cat start weewx inside a Ubuntu container

### ISSUE THREAD

**Issue by JDJoe** [weewx/weewx#786]
starting weewex gives me the following error:

 * Starting weewx weather system weewx                                                                                                                                                              --- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 983, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 904, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 986, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.10/logging/handlers.py", line 915, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/share/weewx/weewxd", line 248, in <module>
    main()
  File "/usr/share/weewx/weewxd", line 101, in main
    log.info("Initializing weewx version %s", weewx.__version__)
Message: 'Initializing weewx version %s'
Arguments: ('4.8.0',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 983, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 904, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 986, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.10/logging/handlers.py", line 915, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/share/weewx/weewxd", line 248, in <module>
    main()
  File "/usr/share/weewx/weewxd", line 102, in main
    log.info("Using Python %s", sys.version)
Message: 'Using Python %s'
Arguments: ('3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 983, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 904, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 986, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.10/logging/handlers.py", line 915, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/share/weewx/weewxd", line 248, in <module>
    main()
  File "/usr/share/weewx/weewxd", line 103, in main
    log.info("Platform %s", platform.platform())
Message: 'Platform %s'
Arguments: ('Linux-4.14.24-qnap-x86_64-with-glibc2.35',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 983, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 904, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 986, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.10/logging/handlers.py", line 915, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/share/weewx/weewxd", line 248, in <module>
    main()
  File "/usr/share/weewx/weewxd", line 104, in main
    log.info("Locale is '%s'", locale.setlocale(locale.LC_ALL))
Message: "Locale is '%s'"
Arguments: ('LC_CTYPE=C.UTF-8;LC_NUMERIC=C;LC_TIME=C;LC_COLLATE=C;LC_MONETARY=C;LC_MESSAGES=C;LC_PAPER=C;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=C;LC_IDENTIFICATION=C',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 983, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 904, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 986, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.10/logging/handlers.py", line 915, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/share/weewx/weewxd", line 248, in <module>
    main()
  File "/usr/share/weewx/weewxd", line 105, in main
    log.info("Using configuration file %s", config_path)
Message: 'Using configuration file %s'
Arguments: ('/etc/weewx/weewx.conf',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 983, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 904, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 986, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.10/logging/handlers.py", line 915, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/share/weewx/weewxd", line 248, in <module>
    main()
  File "/usr/share/weewx/weewxd", line 106, in main
    log.info("Debug is %s", weewx.debug)
Message: 'Debug is %s'
Arguments: (0,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 983, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 904, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 986, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.10/logging/handlers.py", line 915, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/share/weewx/weewxd", line 248, in <module>
    main()
  File "/usr/share/weewx/weewxd", line 135, in main
    log.info("PID file is %s", options.pidfile)
Message: 'PID file is %s'
Arguments: ('/var/run/weewx.pid',)

**Comment by tkeffer** [comment]
The issues list is for tracking bugs and features. For general support questions, use the [weewx-user group](https://groups.google.com/forum/#!forum/weewx-user).

**Comment by JDJoe** [comment]
It requires a Google account so I made one and I still can't post there.

**Comment by tkeffer** [comment]
It must be something you're doing wrong. Thousands of people have posted to weewx-user. Try again.
