### ISSUE TITLE
Repeater_ID setting in wee_device does not work correctly

### ISSUE THREAD

**Issue by eardkdw** [weewx/weewx#863]
In version 4.10.2, if you issue:

`sudo wee_device --set-transmitter-type=5,4,b`

you get

```Using configuration file /etc/weewx/weewx.conf
Using Vantage driver version 3.5.2 (weewx.drivers.vantage)
Proceeding will set channel 5 to type 4 (wind), repeater: B, active.
Are you sure you want to proceed (y/n)? y
Traceback (most recent call last):
  File "/usr/share/weewx/wee_device", line 76, in <module>
    main()
  File "/usr/share/weewx/wee_device", line 72, in main
    device.configure(config_dict)
  File "/usr/share/weewx/weewx/drivers/__init__.py", line 67, in configure
    self.do_options(options, parser, config_dict, not options.noprompt)
  File "/usr/share/weewx/weewx/drivers/vantage.py", line 2181, in do_options
    self.set_transmitter_type(station, options.set_transmitter_type, options.noprompt)
  File "/usr/share/weewx/weewx/drivers/vantage.py", line 2675, in set_transmitter_type
    station.setTransmitterType(channel, transmitter_type, extra_temp, extra_hum, repeater)
  File "/usr/share/weewx/weewx/drivers/vantage.py", line 1061, in setTransmitterType
    raise weewx.ViolatedPrecondition("Invalid repeater %d" % repeater_id)
weewx.ViolatedPrecondition: Invalid repeater 9
```

`sudo wee_device --set-transmitter-type=5,4,a` works, but sets the Repeater channel to H

```TRANSMITTERS: 
  Channel   Receive   Repeater  Type
     1      inactive    none    (N/A)
     2      inactive    none    (N/A)
     3      inactive    none    (N/A)
     4      inactive    none    (N/A)
     5      active      H       wind 
     6      inactive    none    (N/A)
     7      inactive    none    (N/A)
     8      inactive    none    (N/A)
```

it looks like the indices in the `repeater_dict` dictionary attribute for the Vantage class in `vantage.py` are incorrect.

**Comment by tkeffer** [comment]
Fixed in commit https://github.com/weewx/weewx/commit/6b7e3946921ccd761a14fcfd6348877accd60d33, to appear in V5.
