### ISSUE TITLE
Error being logged.

### ISSUE THREAD

**Issue by genesispc** [weewx/weewx#866]
I've been seeing the following error recently not sure what is going on. Looks like some file is missing.

I am running mitct02/weewx docker image (/ https://registry.hub.docker.com/r/mitct02/weewx/) on a Synology NAS. It use to work in the past not sure wy it now fails? Any hints on how to debug this?

--- Logging error ---
Traceback (most recent call last):
  File "/home/weewx/bin/user/interceptor.py", line 2550, in genLoopPackets
    data = self._device.get_queue().get(True, self._queue_timeout)
  File "/usr/lib/python3.10/queue.py", line 179, in get  raise Empty
_queue. Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 987, in emit self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 908, in _connect_unixsocket self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 990, in emit self._connect_unixsocket(self. Address)
  File "/usr/lib/python3.10/logging/handlers.py", line 919, in _connect_unixsocket  self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/home/weewx/bin/weewxd", line 249, in <module> main()
  File "/home/weewx/bin/weewxd", line 154, in main engine. Run()
  File "/home/weewx/bin/weewx/engine.py", line 208, in run for packet in self.console.genLoopPackets():
  File "/home/weewx/bin/user/interceptor.py", line 2566, in genLoopPackets logdbg('empty queue')
  File "/home/weewx/bin/user/interceptor.py", line 284, in logdbg log. Debug(msg)
Message: 'empty queue'
Arguments: ()

**Comment by tkeffer** [comment]
I am sorry, but the interceptor driver is not part of WeeWX.

Try posting to the [user group](https://groups.google.com/g/weewx-user).
