### ISSUE TITLE
wee_extension fails if there are no line "restful_services"

### ISSUE THREAD

**Issue by cryptax** [weewx/weewx#886]
This is a _minor_ issue.
My `weewx.conf` had no `restful_services` which caused an error for the installer. To my understanding, this is an error with `wee_extension`, not the extension weewx-mastodon?

```
$ sudo wee_extension --install weewx-mastodon.zip 
Request to install 'weewx-mastodon.zip'
Extracting from zip archive weewx-mastodon.zip
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 92, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 84, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 130, in install_extension
    self.install_from_dir(extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 203, in install_from_dir
    self.config_dict['Engine']['Services'][service_group])
  File "/usr/lib/python3/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'restful_services'
```

I fixed it by adding an empty line:

```
restful_services = 
```

and then it worked:

```
$ sudo wee_extension --install weewx-mastodon.zip 
Request to install 'weewx-mastodon.zip'
Extracting from zip archive weewx-mastodon.zip
Saving installer file to /usr/share/weewx/user/installer/wxtoot
Saved configuration dictionary. Backup copy at /etc/weewx/weewx.conf.20230827161424
Finished installing extension 'weewx-mastodon.zip'
```

I think wee_extension should not fail if no `restful_services` line.

This is with weewx 4.10.2

**Comment by tkeffer** [comment]
Thanks for spotting this! Fixed in commit https://github.com/weewx/weewx/commit/f368b521a5e77779ce09c883eb7d86c282c31e4e

To appear in V5.
