### ISSUE TITLE
'weectl extension install' fails on deb/rpm installation

### ISSUE THREAD

**Issue by matthewwall** [weewx/weewx#926]
i'm trying to install extensions on a redhat 9.3 installation, weewx 5.0.1 installed from rpm/deb.  there is no `$HOME/weewx-data` directory, just `/etc/weewx`.

```
[vagrant@localhost ~]$ weectl extension install weewx-exfoliation-master.zip 
Using configuration file /etc/weewx/weewx.conf
Install extension 'weewx-exfoliation-master.zip' (y/n)? y
Extracting from zip archive weewx-exfoliation-master.zip
Traceback (most recent call last):
  File "/usr/share/weewx/weectl.py", line 74, in <module>
    main()
  File "/usr/share/weewx/weectl.py", line 66, in main
    namespace.func(namespace)
  File "/usr/share/weewx/weectllib/__init__.py", line 121, in dispatch
    namespace.action_func(config_dict, namespace)
  File "/usr/share/weewx/weectllib/extension_cmd.py", line 116, in install_extension
    ext.install_extension(namespace.source, no_confirm=namespace.yes)
  File "/usr/share/weewx/weecfg/extension.py", line 138, in install_extension
    extension_name = self._install_from_file(extension_path, filetype)
  File "/usr/share/weewx/weecfg/extension.py", line 168, in _install_from_file
    extension_name = self.install_from_dir(extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 185, in install_from_dir
    self._install_files(installer['files'], extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 269, in _install_files
    shutil.copy(source_path, destination_path)
  File "/usr/lib64/python3.9/shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.9/shutil.py", line 266, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/weewx/skins/exfoliation/almanac.html.tmpl'
```

```
[vagrant@localhost ~]$ ls -la /etc/weewx
total 52
drwxr-xr-x. 11 weewx weewx   181 Feb  4 21:20 .
drwxr-xr-x. 81 root  root   8192 Feb  4 21:20 ..
drwxr-xr-x.  3 weewx weewx    18 Feb  4 21:20 bin
drwxr-xr-x.  8 weewx weewx   166 Feb  4 21:20 examples
drwxr-xr-x.  2 weewx weewx   135 Feb  4 21:20 import
drwxr-xr-x.  2 weewx weewx    19 Feb  4 21:20 logrotate.d
drwxr-xr-x.  4 weewx weewx    33 Feb  4 21:20 logwatch
drwxr-xr-x.  2 weewx weewx    24 Feb  4 21:20 rsyslog.d
drwxrwsr-x.  8 weewx weewx    93 Feb  4 21:20 skins
drwxr-xr-x.  2 weewx weewx    49 Feb  4 21:20 systemd
drwxr-xr-x.  2 weewx weewx    25 Feb  4 21:20 udev
-rw-r--r--.  1 weewx weewx 19463 Feb  4 21:20 weewx.conf
-rw-r--r--.  1 weewx weewx 19463 Feb  4 21:19 weewx.conf-5.0.1
```

```
[vagrant@localhost ~]$ grep weewx /etc/group
weewx:x:988:vagrant
[vagrant@localhost ~]$ grep weewx /etc/passwd
weewx:x:989:988::/var/lib/weewx:/sbin/nologin
```

**Comment by matthewwall** [comment]
this is a permissions problem, fixed by the `5.0.1-3` packages
