### ISSUE TITLE
29th February and `archiveSpanSpan`

### ISSUE THREAD

**Issue by roe-dl** [weewx/weewx#941]
On the 29th February the function `archiveSpanSpan` can return an error:

```
Feb 29 12:05:36 LokalWiki weewx[620098] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'user.belchertown.HighchartsJsonGenerator'
Feb 29 12:05:36 LokalWiki weewx[620098] ERROR weewx.reportengine:         ****  day is out of range for month
Feb 29 12:05:36 LokalWiki weewx[620098] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Feb 29 12:05:36 LokalWiki weewx[620098] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 201, in run
Feb 29 12:05:36 LokalWiki weewx[620098] ERROR weewx.reportengine:         ****      obj.start()
Feb 29 12:05:36 LokalWiki weewx[620098] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 394, in start
Feb 29 12:05:36 LokalWiki weewx[620098] ERROR weewx.reportengine:         ****      self.run()
Feb 29 12:05:36 LokalWiki weewx[620098] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 2536, in run
Feb 29 12:05:36 LokalWiki weewx[620098] ERROR weewx.reportengine:         ****      span_start, span_stop = archiveSpanSpan(
Feb 29 12:05:36 LokalWiki weewx[620098] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weeutil/weeutil.py", line 341, in archiveSpanSpan
Feb 29 12:05:36 LokalWiki weewx[620098] ERROR weewx.reportengine:         ****      start_dt = time_dt.replace(year=year, month=month)
Feb 29 12:05:36 LokalWiki weewx[620098] ERROR weewx.reportengine:         ****  ValueError: day is out of range for month
Feb 29 12:05:36 LokalWiki weewx[620098] ERROR weewx.reportengine:         ****  Generator terminated
```

I guess it is not a problem of the Belchertown skin but of the function `weewx.weeutil.archiveSpanSpan`. The function uses `replace` to set a new year and month. The error happens if the year is replaced by a year that does not include a 29th of February. I copied the relevant lines into the Python interpreter:

```
user@LokalWiki:~$ python3
Python 3.8.10 (default, Nov 22 2023, 10:22:35)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> x = datetime.datetime(2024,2,29,11,55,10)
>>> x.replace(year=2023,month=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: day is out of range for month
>>>
```

**Comment by tkeffer** [comment]
I installed the Belchertown skin, ran it using `weectl report run`, and it worked fine.

I need more information than what was provided. What was the tag that created the error?

**Comment by roe-dl** [comment]
Rich is right. It uses `month_delta`. If that option is deprecated, I guess, we can close this issue.

**Comment by roe-dl** [comment]
So sorry for bothering you with this issue. I saw the error messages today in the morning, knowing that it could be fixed today only, and I had no time to look into it.

**Comment by tkeffer** [comment]
Don't be sorry! You have a sharp eye and have found many bugs. I wish everyone was as observant.
