### ISSUE TITLE
WeeWX no longer generates images

### ISSUE THREAD

**Issue by erozen** [weewx/weewx#974]
Running version WeeWX 4.10.2 under docker.  Whenever it tries to generate images the below appears in the logs:

```Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.imagegenerator.ImageGenerator'
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****  type object 'ImageDraw' has no attribute 'textsize'
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 197, in run
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****      obj.start()
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 385, in start
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****      self.run()
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/imagegenerator.py", line 42, in run
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****      self.gen_images(self.gen_ts)
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weewx/imagegenerator.py", line 114, in gen_images
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****      image = plot.render()
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****              ^^^^^^^^^^^^^
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weeplot/genplot.py", line 212, in render
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****      self._renderBottom(draw)
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weeplot/genplot.py", line 404, in _renderBottom
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****      bottom_label_size = draw.textsize(self.bottom_label, font=bottom_label_font)
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****    File "/home/weewx/bin/weeplot/genplot.py", line 646, in textsize
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****      return ImageDraw.ImageDraw.textsize(self, string, **options)
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****  AttributeError: type object 'ImageDraw' has no attribute 'textsize'
Sep 11 18:46:12 weewx[18] ERROR weewx.reportengine:         ****  Generator terminated
Traceback (most recent call last):
  File "/home/weewx/bin/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/home/weewx/bin/weewx/reportengine.py", line 385, in start
    self.run()
  File "/home/weewx/bin/weewx/imagegenerator.py", line 42, in run
    self.gen_images(self.gen_ts)
  File "/home/weewx/bin/weewx/imagegenerator.py", line 114, in gen_images
    image = plot.render()
            ^^^^^^^^^^^^^
  File "/home/weewx/bin/weeplot/genplot.py", line 212, in render
    self._renderBottom(draw)
  File "/home/weewx/bin/weeplot/genplot.py", line 404, in _renderBottom
    bottom_label_size = draw.textsize(self.bottom_label, font=bottom_label_font)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weewx/bin/weeplot/genplot.py", line 646, in textsize
    return ImageDraw.ImageDraw.textsize(self, string, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ImageDraw' has no attribute 'textsize'
```

Last successful image generation was February 2023, so breaking change was sometime before then.

**Comment by tkeffer** [comment]
The breaking change is actually in Pillow: Pillow v10 removed the attribute `textsize`. For example, see this thread: https://groups.google.com/g/weewx-user/c/F1oLMD8_3MQ/m/Gir1m-9RAgAJ So, you must have upgraded Pillow sometime since Feb. 2023. 

WeeWX V5 has a fix to avoid this error.

Your choice is to either downgrade to Pillow v9, or upgrade WeeWX to V5.1.
